export {default as TabBar} from './TabBar.vue'
export {default as TabItem} from './TabItem.vue'
export {default as MyButton} from './MyButton.vue'
export {default as MyFootBar} from './MyFootBar.vue'
export {default as MyFootSeparator} from './MyFootSeparator.vue'
export {default as VTabBar} from './VTabBar'
export {default as VTabBarItem} from './VTabBarItem'